apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "tlak8s"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "tlak8s"
    spec:
      containers:
        - name: "tlak8s"
          image: "registrytla.azurecr.io/tlak8s"
          ports:
          - containerPort: 8080
